CartPole-v1:
  policy: "MlpPolicy"
  n_timesteps: !!float 8e4
  buffer_size: 20000
  learning_starts: 1000
  target_update_interval: 250
  exploration_fraction: 0.2
  exploration_final_eps: 0.06
  learning_rate: !!float 1e-3
  batch_size: 64
  train_freq: 32
  gradient_steps: 16
  gamma: 0.99
  optimize_memory_usage: False
